restrict Record alteration if not in an appropriate stage, resolves #62
ideafast/middleware-services pull request #64
Opened 2021-04-01 15:37 UTC by davidverweij

These changes will prevent (in fact throw `ValueError`) if you try to progress a `pipeline_state` in a `Record` if the previous state has not been completed. Resolves #62 

# Testing
This won't affect any of the code as long as it doesn't violate the order of stages. However - this does mean we could consider `try / excepting` complete DAGs or perhaps sections within a DAG to actually catch if this happens possibly. Alternatively, this is more a safety-net for ourselves when coding.
Run:
```python
poetry run nox -r
```

2021-04-01 15:38 UTC, davidverweij commented on data_transfer/schemas/record.py
> +    is_uploaded: bool = False
I didn't understand why these were optional (i.e. could be assigned `None`) if we default them to `False` anyway..

2021-04-06 07:36 UTC, jawrainey requested changes
> This won't affect any of the code as long as it doesn't violate the order of stages. However - this does mean we could consider try / excepting complete DAGs or perhaps sections within a DAG to actually catch if this happens possibly. Alternatively, this is more a safety-net for ourselves when coding.

I would not add try/except around DAGS but instead let it fail. These changes are primarily for developers rather than solving known bugs, i.e., they do not resolve the issue I note in #62 

I've tested this locally by running the tests and also running the DRM pipeline where the bug exists -- an error is thrown which is great and helped confirm where the BUG is. I'll create a seperate PR to resolve the bug.

2021-04-06 07:36 UTC, jawrainey commented on data_transfer/schemas/record.py
> +        return v
Given the logic is the same across these three validators, I would pull it out into a public static method of the Record class, which should be accessible via `cls`.

```python
   @staticmethod
    def value_exists_or_raise(value_exists: bool, record: dict, value: str) -> bool:
        if value_exists and not record[value]:
            _type = value.split("-")[0]
            raise ValueError(f"NOT ALLOWED: this Record is not {_type} yet.")
        return value_exists
```

Then each validator method can call it (I assume) via:

```python
return cls.value_exists_or_raise(v, values, "is_downloaded")
```

This also means you can test the if statement -- so two extra tests: one for fail and one for success.

2021-04-06 07:36 UTC, jawrainey commented on tests/data_transfer_tests/schemas/test_record.py
> +def test_not_allowed_processed(get_record: Record) -> None:
I'd also test some ways that it passes, perhaps by testing `value_exists_or_raise` above?

2021-04-06 10:25 UTC, davidverweij commented
@jawrainey, I've pulled out the method to static as indicated. @ColinBD, can you review this PR overall; and merge if ok? Cheers!

2021-04-06 10:47 UTC, ColinBD commented
All good.

2021-04-06 10:48 UTC, merged